version: '3.9'

services:
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT:-5000}:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/ecommerce}
      - JWT_SECRET=${JWT_SECRET:-changeme}
    command: ["npm", "start"]

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
